name: 更新过去一周网易云音乐的听歌排行
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 */5 * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: -|
          git clone https://github.com/Leecason/netease-music-box.git && cd netease-music-box && yarn install && mv index.js action.yml sample.env node_modules ../
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIST_ID: 193c22826613cd0ec03d0c7bbadb3e0a
          USER_ID: 316286554
          USER_TOKEN: ${{ secrets.USER_TOKEN }}