name: 将最新的哔哩哔哩投稿更新到 gist
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "12 3 */7 * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIST_ID: 8d7784387dec506f58e3421f28024105
          UID: '237149104'
        run: git clone https://github.com/KeJunMao/bilibili-box.git && cd bilibili-box && deno run --allow-net --allow-env index.ts