name: 使用WakaTime统计信息更新要点
on:
  push:
    branches:
      - master
  schedule:
    - cron: "24 3 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIST_ID: 82454e5ea267aa4717f2684dbb09d6b7
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2